# Generated by Django 2.1.4 on 2018-12-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181225_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
